### ISSUE TITLE
Error while running example Notebook

### ISSUE THREAD

**Issue by astariul** [HighCWu/keras-bert-tpu#1]
I tried to run your [Colab demo](https://colab.research.google.com/github/HighCWu/keras-bert-tpu/blob/master/demo/load_model/load_and_predict.ipynb), and I get the following error :

`InvalidArgumentError: NodeDef mentions attr 'layouts' not in Op<name=InfeedEnqueueTuple; signature=inputs: -> ; attr=dtypes:list(type),min=1; attr=shapes:list(shape); attr=device_ordinal:int,default=-1; is_stateful=true>; NodeDef: node infeed-enqueue-infer-0 (defined at <ipython-input-5-14677c7732b6>:25)  = InfeedEnqueueTuple[device_ordinal=0, dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT], layouts=[], shapes=[[1,512], [1,512], [1,512]], _device="/job:worker/device:CPU:0"](infeed-enqueue-Input-Token_10-0, infeed-enqueue-Input-Segment_10-0, infeed-enqueue-Input-Masked_10-0). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).`

---

**Do you have the same error ?**

**Comment by HighCWu** [comment]
It seems because of the tensorflow version update. tf-nightly 1.13.0.dev20181218 still can be used, but tf-nightly==1.13.0.dev20181219 can't, I will check the codes later. If you want to use the colab code right now, add 
```
! pip install tf-nightly==1.13.0.dev20181218 -q
```
under the 'keras-bert-tpu' pip install. @Colanim

**Comment by HighCWu** [comment]
I updated the package dependencies. It's no problem now. But this is temporary. After the 20181218 version of tf-nightly 1.3 officially removes, I will try to fix the problem. Keep issue open

**Comment by murtaza98** [comment]
I tried the above solution u proposed, 
`! pip install tf-nightly==1.13.0.dev20181218 -q`

But here I am getting this error
`Could not find a version that satisfies the requirement tf-nightly==1.13.0.dev20181218 (from versions: 1.13.0.dev20190101, 1.13.0.dev20190102, 1.13.0.dev20190103, 1.13.0.dev20190104, 1.13.0.dev20190108, 1.13.0.dev20190109, 1.13.0.dev20190110, 1.13.0.dev20190111, 1.13.0.dev20190112, 1.13.0.dev20190113, 1.13.0.dev20190114, 1.13.0.dev20190115, 1.13.0.dev20190116, 1.13.0.dev20190117, 1.13.0.dev20190118, 1.13.0.dev20190119, 1.13.0.dev20190120, 1.13.0.dev20190121, 1.13.0.dev20190122, 1.13.0.dev20190123, 1.13.0.dev20190124, 1.13.0.dev20190125, 1.13.0.dev20190203, 1.13.0.dev20190204, 1.13.0.dev20190205, 1.13.0.dev20190206, 1.13.0.dev20190207, 1.13.0.dev20190208, 1.13.0.dev20190211, 1.13.0.dev20190212, 1.13.0.dev20190213, 1.13.0.dev20190214, 1.13.0.dev20190215, 1.13.0.dev20190216, 1.13.0.dev20190217, 1.13.0.dev20190218, 1.13.0.dev20190219, 1.13.0.dev20190220, 1.13.0.dev20190221, 1.13.0.dev20190222, 1.13.0.dev20190223)
No matching distribution found for tf-nightly==1.13.0.dev20181218`

It seems tensorflow has officially removed all 2018 versions of tf-nightly.

Any suggestions on how to resolve this issue?

Thanks in Advance. I truly appreciate your efforts.

**Comment by HighCWu** [comment]
@murtaza98   You can see this issue #2 . I uploaded an old version tf-nightly. If I have time, I'll update the version. I'm not sure the newest tf version is okey.

**Comment by HighCWu** [comment]
I update it to the newest version, have a try. @murtaza98
