### ISSUE TITLE
Can't install yet

### ISSUE THREAD

**Issue by abhiWriteCode** [HighCWu/keras-bert-tpu#2]
Could not find a version that satisfies the requirement tf-nightly<=1.13.0.dev20181218 (from keras-bert-tpu) (from versions: 1.13.0.dev20190101, 1.13.0.dev20190102, 1.13.0.dev20190103, 1.13.0.dev20190104, 1.13.0.dev20190108, 1.13.0.dev20190109, 1.13.0.dev20190110, 1.13.0.dev20190111, 1.13.0.dev20190112, 1.13.0.dev20190113, 1.13.0.dev20190114, 1.13.0.dev20190115, 1.13.0.dev20190116, 1.13.0.dev20190117, 1.13.0.dev20190118, 1.13.0.dev20190119, 1.13.0.dev20190120, 1.13.0.dev20190121, 1.13.0.dev20190122, 1.13.0.dev20190123, 1.13.0.dev20190124, 1.13.0.dev20190125, 1.13.0.dev20190203, 1.13.0.dev20190204, 1.13.0.dev20190205, 1.13.0.dev20190206, 1.13.0.dev20190207)

No matching distribution found for tf-nightly<=1.13.0.dev20181218 (from keras-bert-tpu)

**Comment by HighCWu** [comment]
Try install this first
https://drive.google.com/file/d/1-odjer8iiw7MrXJX8JsQN4Zwrx2M-q8W/view?usp=sharing

**Comment by abhiWriteCode** [comment]
It works.
All the best for your future projects 👍
